name: 'run-did-resolution-test-suite'
description: 'Run did-resolution-test-suite'
inputs:
  host:
    description: 'Host of Uni-Resolver deployment'
    required: false
    default: https://resolver.svip.danubetech.com/1.0/identifiers/
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}